### ISSUE TITLE
teams not being found in the database

### ISSUE THREAD

**Issue by Sakimori** [Sakimori/matteo-the-prestige#20]
showteams and setupgame isn't finding teams with emoji or special characters in their names, it seems

**Comment by Sakimori** [comment]
```
Traceback (most recent call last):
  File "/root/matteo/lib/python3.8/site-packages/discord/client.py", line 333, in _run_event
    await coro(*args, **kwargs)
  File "the_prestige.py", line 163, in on_message
    team = games.get_team(command.split(" ",1)[1])
  File "/root/matteo/games.py", line 461, in get_team
    team_json = jsonpickle.decode(db.get_team(name), keys=True, classes=team)
  File "/root/matteo/database.py", line 217, in get_team
    return team[2] #returns a json string
TypeError: 'NoneType' object is not subscriptable

```

**Comment by internetFionna** [comment]
Bug related to smart punctuation; one team is entered with smart apostrophe (`’`) in lieu of regular apostrophe (`'`). Inputs will be sanitized in future update.
